<?xml version="1.0"?>
<package format="3">
  <name>quadrotor_nmpc_observability</name>
  <version>0.1.0</version>
  <description>Quadrotor NMPC / MPCC / DQ-MPCC in C++ with acados</description>
  <maintainer email="bguevara@laser.ufpb.br">Bryan Guevara</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>quadrotor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
